CREATE DATABASE practice;

CREATE TABLE users (
_id VARCHAR(200) PRIMARY KEY,
name VARCHAR(200),
email VARCHAR(200),
phone NUMERIC(30),
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);


CREATE TABLE todos(
_id VARCHAR(200) PRIMARY KEY,
todos_name VARCHAR(200),
owner VARCHAR REFERENCES users(_id) ON DELETE CASCADE,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);